### ISSUE TITLE
Request explanation of specific operating environment

### ISSUE THREAD

**Issue by zfw-cv** [UCSC-VLAA/MicroDiffusion#2]
Hello author, first of all, I am very grateful for your interesting work. I would like to ask if you can  when this job appears?
training INR is OK, but when running "python train.py", I encountered a series of problems. Also solve some. However, there are still problems. All, I would like to inquire about the specific environment you are using. Thanks.

**Comment by TheFllood** [comment]
Hi, I have uploaded the requirements file, you can check it out.

**Comment by zfw-cv** [comment]
Thanks for the reply. I mainly want to ask about your torch version.

**Comment by TheFllood** [comment]
Hi, torch version==2.3.0 works fine.

**Comment by zfw-cv** [comment]
Hello. According to the torch2.3.0 version requirements you recommended, when I was training, I encountered an error when running python train.py. I speculated that there was a problem with loss.backward(), and it should be that the torch version was wrong. I would like to ask, are you sure there are no problems during operation? Maybe the torch version is a little too high?
The specific error reported is:
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph= True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

**Comment by TheFllood** [comment]
Hi, just remove the two line, I mistakenly kept two consecutive backward.
![image](https://github.com/UCSC-VLAA/MicroDiffusion/assets/71912052/fd03c813-ec13-4530-b4c8-2a6541150239)

**Comment by pluto0528** [comment]
> 嗨，把两行去掉，我错误地连续向后保持了两个。 ![图像](https://private-user-images.githubusercontent.com/71912052/328735328-fd03c813-ec13-4530-b4c8-2a6541150239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTY4MTYsIm5iZiI6MTcxNTE1NjUxNiwicGF0aCI6Ii83MTkxMjA1Mi8zMjg3MzUzMjgtZmQwM2M4MTMtZWMxMy00NTMwLWI0YzgtMmE2NTQxMTUwMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA4MjE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMzQyOGFkMDk5ZGY1ZDExNmVkOGYzNDA4YmRiM2VkNjlhYTE0ZTVhYTA1ZWQ4MThmMmJhNmE0MzFmYmI5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3M7P6Akezi2Aw2yQJk5mLqND-m3F28sr95YZIMGRkso)

Hello, I noticed the same problem,I've removed the excess, and I added 'retain_graph=True' into backward to work properly, but not long after training has started, the dimension of 'rendered' will change, causing the array to cross, Have you encountered this problem? Can you tell me how to solve it?
![e4ec143c5306ef3b15f1ac19e14db4d](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/07d9fe9d-c1c4-40c9-84ed-82e1ef3d9f69)

**Comment by pluto0528** [comment]
> Hi, just remove the two line, I mistakenly kept two consecutive backward. ![image](https://private-user-images.githubusercontent.com/71912052/328735328-fd03c813-ec13-4530-b4c8-2a6541150239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTY5MjMsIm5iZiI6MTcxNTE1NjYyMywicGF0aCI6Ii83MTkxMjA1Mi8zMjg3MzUzMjgtZmQwM2M4MTMtZWMxMy00NTMwLWI0YzgtMmE2NTQxMTUwMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA4MjM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNGViYjMxOTVhMTJiZjMwMTA0MmNmZjRlNTc0YWZmZWJhN2ZlYjJjNjRhZDQyMmI5MmFmZjhjMGRiNTM3ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMPKGxdJ0h8l3MCT-gWCifHBDHFx6fFW4jros4gnFho)

Hello, I noticed the same problem,I've removed the excess, and I added 'retain_graph=True' into backward to work properly, but not long after training has started, the dimension of 'rendered' will change, causing the array to cross, Have you encountered this problem? Can you tell me how to solve it?
![e4ec143c5306ef3b15f1ac19e14db4d](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/2e4081a1-1977-47f5-a765-fc1785a0a8af)

**Comment by TheFllood** [comment]
Which dataset did you use?  The z_total  should change with different dataset, for Dendrite: 236, Vasculature:130, Neuron: 136.

**Comment by pluto0528** [comment]
Sorry，this is my first exposure to 3D generation in the biological field，Is there any order in which these datasets are used？The following is the process of running the code. I hope you can point out the error to me. Thank you very much.
First, there are no errors in training the INR,the dataset I'm using here is neurons.npy in the gt folder,because I saw that the comments given in the code looked like this.
![5cf003e6285dec464b88fd664171b51](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/eefc0d40-3d89-4533-af88-ceafe83c384a)
next,I used the latest_nerf generated during INR training as dataset_name and dendrite.npy as gt_path，This will lead to the mistake I told you about earlier. I tried neurons.npy as gt_path, but there was a dimension error.
![2e851c250e28fc61905d695eb3c83ef](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/0f536003-5c5c-48f9-af3c-d98c7f8cff2f)
![2a8b1a7988051733804de869572d25f](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/bad75449-2131-405e-848b-b08557ce5922)

**Comment by TheFllood** [comment]
Hi, If you use neurons.npy as gt, then the dataset name is neurons.
And you should rename the weight of inr model to the dataset name, for example [neurons.pth](https://www.dropbox.com/scl/fi/m0pm0e6aino3s0j6q30if/neurons.pth?rlkey=rklc0nkdih95ah9jiotofjhtn&st=vzlkp5g1&dl=0), and change the 
![image](https://github.com/UCSC-VLAA/MicroDiffusion/assets/71912052/8cc65a35-4248-4d1e-ae67-062da1c26694) to where the inr weight is. 

At the same time change 
![image](https://github.com/UCSC-VLAA/MicroDiffusion/assets/71912052/3507c2d7-42a1-40d9-9042-ac9177c730e7)
to 136 for neurons training.

**Comment by pluto0528** [comment]
Thank you very much,when I set z_total=236, the program run successfully, but I have a question, this is the running instruction
![2b9df90c80e77d4887648df7ea1ae7c](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/feef6343-bb8d-4e8b-8b4c-c77a19e05f0a)the weights of the inr model are trained with neurons.npy. Why is dendrite.npy used for gt_path here instead of neurons.npy?Same error occurs when I set gt_path=neurons.npy and z_total=136
![b6d19175b6f411c80e93dd8ad154054](https://github.com/UCSC-VLAA/MicroDiffusion/assets/169243680/65c2ff96-a230-4cba-8676-123d144b3d85)

**Comment by TheFllood** [comment]
If you train inr with neurons.npy, the dataset name is neurons and gt path is neurons.npy. I have update the code, and test gt_path=neurons.npy and z_total=136, it works fine now.

**Comment by pluto0528** [comment]
Thank you for your patient answer, I wish you a happy life！
